services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: keeptrack
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres-data: